[processor.pyrefly]
enabled = false
exclude_dirs = ["/not_mine/"]

[processor.make]
exclude_files = ["Makefile"]

[processor.spellcheck]
use_words_file = true

[processor.cc_single_file]
include_paths = [
	"/usr/include/python3.13",
]
exclude_dirs = ["/bad_lib/", "/crashing_python/", "/embedding_python_in_c/", "/extending_python_with_c/"]

[analyzer.cpp]
include_paths = [
	"/usr/include/python3.13",
]

[processor.cppcheck]
args = [
	"--error-exitcode=1",
	"--enable=warning,style,performance,portability",
	"--inline-suppr",
]

[processor.pylint]
exclude_paths = [
	"to_integrate",
]
